# Generated by Django 3.2 on 2022-01-09 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('custom_user', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
            ],
        ),
    ]
