# Generated by Django 3.2 on 2022-01-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
        ('chat', '0004_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='users.customuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chat.group')),
            ],
        ),
    ]
